.github/workflows/lint.yml, .github/workflows/pages.yml, .github/workflows/release.yml, .github/workflows/test.yml, .gitignore, build.py, poetry.lock, pyproject.toml, src/ares/cython/cython_functions.pyi, src/ares/cython/cython_functions.pyx
To be continued: Integrate cython with poetry, so that `poetry install` will compile cython. For now the following will compile `cython` files:
`python build.py build_ext --inplace`
=> build: compile cython

src/ares/managers/unit_cache_manager.py
Small refactor on catch enemy unit included, look out for any bugs
=> refactor: replace `defaultdict` with `dict` in unit cache manager

src/ares/build_runner/build_order_runner.py, src/ares/consts.py, src/ares/managers/building_manager.py, src/ares/managers/resource_manager.py
The main motivation here is the first scv building a depot also builds the barracks
=> feat: persistent building worker

poetry.lock
Nothing other then a poetry lock file
=> build: update python-sc2

src/ares/behaviors/macro/mining.py, src/ares/behaviors/macro/spawn_controller.py, src/ares/cython_extensions/combat_utils.pyx, src/ares/managers/building_manager.py, src/ares/managers/hub.py, src/ares/managers/manager_mediator.py
Vague PR title, but various things that I couldn't be bothered to open separate PR's for
=> feat: ares updates and fixes

docs/combat_behaviors.md, src/ares/behaviors/combat/individual/__init__.py, src/ares/behaviors/combat/individual/stutter_unit_forward.py, src/ares/build_runner/build_order_runner.py, src/ares/managers/building_manager.py, src/ares/managers/path_manager.py, src/ares/managers/placement_manager.py, src/ares/managers/unit_memory_manager.py
Fixed 2 crashes and a few bugs found in some of phobos's ladder games
=> feat: ladder fixes

notebooks/geometry_and_terrain_cython.ipynb, notebooks/python_to_cython.ipynb, src/ares/behaviors/macro/mining.py, src/ares/build_runner/build_order_runner.py, src/ares/cython_extensions/combat_utils.pyi, src/ares/cython_extensions/combat_utils.pyx, src/ares/cython_extensions/geometry.pyi, src/ares/cython_extensions/geometry.pyx, src/ares/cython_extensions/units_utils.pyi, src/ares/cython_extensions/units_utils.pyx, src/ares/managers/building_manager.py, src/ares/managers/path_manager.py, src/ares/managers/resource_manager.py
Applied functions where appropriate in code for testing, still need to go through and replace all existing python code these functions can replace
=> feat: cython functions

src/ares/__init__.py, src/ares/behaviors/combat/individual/__init__.py, src/ares/behaviors/combat/individual/worker_kite_back.py, src/ares/config.yml, src/ares/custom_bot_ai.py, src/ares/cython_extensions/units_utils.pyi, src/ares/managers/building_manager.py, src/ares/managers/hub.py, src/ares/managers/placement_manager.py, src/ares/managers/resource_manager.py
And some other general maintanence
=> feat: add worker kiting behavior

src/ares/behaviors/macro/mining.py, src/ares/build_runner/build_order_runner.py
This is almost twice as slow as using a try except, exponentially expensive as the number of miners grow Might want to replace this in other areas of the code
=> perf: replace dict.get() calls in mining

src/ares/behaviors/macro/mining.py, src/ares/config.yml
Approximately 2% improved mining rate, mostly since townhall radius was wrong
=> feat: mining optimization

poetry.lock, src/ares/behaviors/macro/mining.py, src/ares/behaviors/macro/spawn_controller.py, src/ares/build_runner/build_order_runner.py, src/ares/consts.py, src/ares/cython_extensions/general_utils.pyi, src/ares/cython_extensions/general_utils.pyx, src/ares/dicts/structure_to_building_size.py, src/ares/managers/building_manager.py, src/ares/managers/manager_mediator.py, src/ares/managers/placement_manager.py
- cython pylon matrix covers function
- protoss building formation, with updated build runner usage
BREAKING CHANGE: due to new argument types in `placement_manager.can_place_structure` and `placement_manager.request_building_placement`
=> feat: building formation

src/ares/behaviors/macro/__init__.py, src/ares/behaviors/macro/auto_supply.py, src/ares/behaviors/macro/build_structure.py, src/ares/behaviors/macro/macro_plan.py, src/ares/behaviors/macro/spawn_controller.py, src/ares/consts.py, src/ares/main.py, src/ares/managers/building_manager.py
Other then some rudimentary tests with each race, this has not been fully scrutinized. Will need future bug fixes and tweaks.
Behaviors implemented:
- `AutoSupply()`
- `BuildStructure()` - only works for T and P via the `PlacementManager`
- `MacroPlan()` - To stack multiple `MacroBehavior`'s
=> feat: auto supply

src/ares/main.py
Previously behaviors were executed a frame/step later then expected
=> fix: behaviors execute on correct frame

.flake8, tests/conftest.py, tests/load_bot_from_pickle.py, tests/managers/test_ability_tracker_manager.py, tests/managers/test_building_manager.py, tests/managers/test_data_manager.py, tests/managers/test_placement_manager.py, tests/managers/test_resource_manager.py, tests/managers/test_unit_role_manager.py, tests/test_manager_mediator.py
Setup test infrastructure from pickled files and add initial tests
Many more tests to write ...
=> test: add tests

docs/api_reference/behaviors/macro_behaviors.md, src/ares/behaviors/macro/__init__.py, src/ares/behaviors/macro/addon_swap.py, src/ares/behaviors/macro/auto_supply.py, src/ares/behaviors/macro/build_structure.py, src/ares/behaviors/macro/mining.py, src/ares/behaviors/macro/spawn_controller.py, src/ares/build_runner/build_order_parser.py, src/ares/build_runner/build_order_runner.py, src/ares/consts.py, src/ares/managers/flying_structure_manager.py, src/ares/managers/hub.py, src/ares/managers/manager_mediator.py, src/ares/managers/placement_manager.py
Includes a flying structure manager for any generic flying structure tracking, and a specific `AddonSwap` `Behavior` which makes use of this manager that can be imported into user's bot.
=> feat: addon swaps

src/ares/consts.py
Had something I required, added some others that come to mind
=> feat: extra unit roles

docs/index.md, src/ares/behaviors/combat/individual/drop_cargo.py, src/ares/behaviors/combat/individual/pick_up_cargo.py, src/ares/behaviors/combat/individual/place_predictive_aoe.py, src/ares/behaviors/combat/individual/shoot_target_in_range.py, src/ares/behaviors/maneuver_recipes/dropship_recipes.py, src/ares/behaviors/maneuver_recipes/general_unit_recipes.py, src/ares/behaviors/maneuver_recipes/ranged_micro_recipes.py
Found that there are common behaviors that get stacked
=> feat: behavior recipes

src/ares/behaviors/combat/group/keep_group_safe.py, src/ares/managers/resource_manager.py, src/ares/managers/squad_manager.py
There was a bug where units got removed from a squad but since they were still present in `self_assigned_unit_tags` they never get reassigned,
=> fix: squad clean up

src/ares/behaviors/combat/group/a_move_group.py, src/ares/behaviors/combat/group/combat_group_behavior.py, src/ares/behaviors/combat/group/stutter_group_back.py, src/ares/behaviors/combat/group/stutter_group_forward.py, src/ares/build_runner/build_order_runner.py
Refactoring / fixes / tweaks to group combat behaviors mostly
=> feat: group behavior tweaks

poetry.lock, pyproject.toml, src/ares/behaviors/macro/spawn_controller.py
Updated ids, and merged latest burny-sc2 changes into our custom fork
=> fix: zerg morphs work correctly in spawn controller

src/ares/behaviors/combat/individual/shoot_target_in_range.py, src/ares/managers/path_manager.py
=> fix: prevent changeling influence being added

src/ares/managers/building_manager.py
Before attempting to remove from building tracker
=> fix: ensure target has value in building tracker

docs/tutorials/build_runner.md, src/ares/build_runner/build_order_parser.py, src/ares/build_runner/build_order_runner.py, src/ares/consts.py, src/ares/custom_bot_ai.py
Also support `core` and `gate` as valid build order command strings
=> feat: build runner support upgrades

docs/tutorials/build_runner.md, src/ares/behaviors/macro/spawn_controller.py, src/ares/build_runner/build_order_parser.py, src/ares/build_runner/build_order_runner.py, src/ares/consts.py, src/ares/custom_bot_ai.py, src/ares/main.py, src/ares/managers/manager_mediator.py, src/ares/managers/placement_manager.py
Simulates warp in placement queries
`SpawnController` supports warp ins
Build runner target options
=> feat: support gateway warpins

src/ares/managers/placement_manager.py
Found this rare bug while testing, run placement query to slightly adjust warp in placement if needed
=> fix: run game placement query to ensure warpin placement

docs/index.md
=> feat: Add 12PoolBot to list of bots

src/ares/managers/placement_manager.py
If unable to find protoss placement at requested base, search other base locations for a valid placement
=> fix: search pylons at alternative bases for placement

src/ares/behaviors/macro/production_controller.py
The new version handles army compositions with a single unit, and now supports adding extra production if bot is building up a bank based on how much production can be supported by current income level.
=> feat: production controller rewrite

src/ares/managers/placement_manager.py
This prevents some instances where T can block units
=> fix: prevent 3x3 too close to existing T wall

poetry.lock, src/ares/behaviors/macro/gas_building_controller.py
Also removed the dependency on `setuptools` from `map_analyzer`
=> fix: gas building controller max pending works for Terran

poetry.lock, src/ares/behaviors/combat/individual/__init__.py, src/ares/behaviors/combat/individual/speed_mining.py, src/ares/behaviors/macro/mining.py, src/ares/config.yml
Previously only flee if taking damage
Refactored speed mining into own behavior
=> feat: mining workers can flee if danger too high

src/ares/managers/warp_in_manager.py
Simplified this so it works 100% consistently, all be it not as accurate
Revisit later
=> fix: simplify warp-in logic

src/ares/building_placements.yml
Add protoss natural wall placements for current ladder maps
Add rest when final map pool is finalized
=> fix: add missing building placements for current maps

src/ares/build_runner/build_order_parser.py, src/ares/managers/terrain_manager.py
Changed some properties in terrain manager to cached_property for optimization purposes
=> fix: `ol_spot_near_enemy_natural` mediator request works

src/ares/consts.py, src/ares/main.py
Previously buildings think they could build shortly before reactor was finished
=> fix: ensure reactored structures are ready to build

docs/api_reference/behaviors/combat_behaviors.md, src/ares/behaviors/combat/individual/__init__.py, src/ares/behaviors/combat/individual/nydus_path_unit_to_target.py, src/ares/behaviors/combat/individual/queen_spread_creep.py, src/ares/behaviors/combat/individual/tumor_spread_creep.py, src/ares/behaviors/macro/production_controller.py, src/ares/build_runner/build_order_parser.py, src/ares/build_runner/build_order_runner.py, src/ares/consts.py, src/ares/custom_bot_ai.py, src/ares/managers/creep_manager.py, src/ares/managers/hub.py, src/ares/managers/manager_mediator.py, src/ares/managers/nydus_manager.py, src/ares/managers/path_manager.py, src/ares/managers/unit_memory_manager.py
Allow users to find nydus location given a location
Pathfinding method to take into account nyduses
Convenient `NydusPathUnitToTarget` behavior to support pathfinding via nyduses
Add some missing behaviors to the docs
Cancel gas option for the build runner
=> feat: add nydus manager

src/ares/building_placements.yml
Added New Map loc for new maps
=> chore: update building placements for patch 5.0.14 maps
